### PR TITLE
Adding the ability to specify the stack when creating code package

### PR DESCRIPTION
**Pull request by kingsimmy**
Adding the ability to construct a JavaCode object specifying the stack e.g. "java-1.8". 
If stack is populated it will be put on the request when doing client.createCode

### CODE REVIEW

**Comment by kingsimmy** [comment]
Any update on this pull request?

**Comment by treeder** [comment]
@edsrzf can you take a look at this?

**Comment by kingsimmy** [comment]
@edsrzf @treeder is it possible for you to merge this small addition?

**Comment by rkononov** [comment]
@pyeremenko maybe you could review this one?

**Comment by treeder** [comment]
@kingsimmy this needs to be backwards compatible. Could do this with method overloading rather than replacing methods.

**Comment by kingsimmy** [comment]
Thanks for the feedback @treeder 
I've added a commit to this pull request. Now existing method signatures maintain backwards compatibility and new functionality is added by method overloading. Please let me know if this looks okay.

**Comment by treeder** [comment]
Ok, @edsrzf will review and merge.

**Comment by kingsimmy** [comment]
Hi @treeder  @edsrzf is this ready to be merged?

**Comment by kingsimmy** [comment]
@treeder @edsrzf Please can you merge this.

Thanks

**Comment by treeder** [comment]
@edsrzf @nicksardo can one of you look at this?

**Comment by nicksardo** [comment]
Looks like this will send stack=_empty string_ if using the old JavaCode constructor (no stack specified) - not sure how IronWorker api will handle that. Instead of introducing one more param, I'm thinking `codesCreate(...)` should take a map of options to support `retries`, `max_concurrency`, `config`, etc... similar to a task creation. Instead of adding these options to the BaseCode class, they could be an optional second parameter for `createCode(...)`.  Thoughts?

**Comment by kingsimmy** [comment]
Or we can easily change codesCreate to
if(stack != null){
    params.put("stack", stack);
}

**Comment by nicksardo** [comment]
Yes, but the branch still doesn't accommodate the other options. It's inevitable that someone will come along requesting `max_concurrency`.

**Comment by kingsimmy** [comment]
I've made the change to handle when stack is not specified.

Please could we merge it now. I've been waiting 5 months for this basic change.

**Comment by kingsimmy** [comment]
@treeder @nicksardo @edsrzf Please could you merge this. I am keen to be able to start using IronWorker again with Java1.8 stack

**Pull request merged**
