### PR TITLE
Return a boolean value as a cancellation state

### PR DESCRIPTION
**Pull request by sunloverz**

### CODE REVIEW

**Comment by treeder** [comment]
Seems like this isn't backwards compatible, or is it?

**Comment by treeder** [comment]
And why not return the entire response with status code and all if we're going to return anything.

**Comment by sunloverz** [comment]
It is backward compatible, I think its better to return a boolean value like in iron_dotnet. We also can return "Cancelled" string value

**Comment by treeder** [comment]
Need to be released to Maven or anything @sunloverz ?

**Comment by sunloverz** [comment]
@treeder gonna release now

**Pull request merged**
